version: '3'
services:
  todayku-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/todayku
      - NODE_ENV=development
      - JWT_SECRET=dev_secret_key_change_in_production
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todayku
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: