app = "todayku"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

[env]
  NODE_ENV = "production"

[deploy]
  strategy = "rolling"